/*
Copyright © 2020 NAME HERE <EMAIL ADDRESS>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package main

import (
	"context"

	"github.com/spf13/cobra"

	"ocibundle/internal/action"
)

var patchOpts action.PatchOpts

// patchCmd applies patch to target the form of OCI-image layout
var patchCmd = &cobra.Command{
	Use:           "patch [PATCH_PATH]",
	Short:         "apply patch file, the targets are written in patch file if patch file is generated by `diff' cmd",
	SilenceUsage:  true,
	SilenceErrors: true,
	Args:          cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		return action.Patch(context.TODO(), args[0], &patchOpts)
	},
}

func init() {
	rootCmd.AddCommand(patchCmd)
	flag := patchCmd.Flags()
	flag.StringVarP(&patchOpts.Origin, "source", "s", "", "specified a source reference, it will be ignored if patch file is standard (generated by `diff' cmd)")
}
